server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lnkz}
    username: ${SPRING_DATASOURCE_USERNAME:lnkz}
    password: ${SPRING_DATASOURCE_PASSWORD:lnkz}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

jwt:
  signing-key: ${JWT_SIGNING_KEY:change-me-too}

